### ISSUE TITLE
Electron failed to install correctly

### ISSUE THREAD

**Issue by wenjialu** [onblog/BlogHelper#59]
1. 你使用的操作系统是：macOS Big Sur

2. 你使用的本软件版本号是：最新

3. 请详细叙述你的问题：
npm start 后出现以下提示：

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/Volumes/UNTITLED/BlogHelper-master/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/Volumes/UNTITLED/BlogHelper-master/node_modules/electron/index.js:18:18)

删掉重装
npm install electron --verbose

还是一样的报错

4. 用于问题复现的数据：

**Comment by wenjialu** [comment]
> 1. 你使用的操作系统是：macOS Big Sur
> 2. 你使用的本软件版本号是：最新
> 3. 请详细叙述你的问题：
>    npm start 后出现以下提示：
> 
> Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
> at getElectronPath (/Volumes/UNTITLED/BlogHelper-master/node_modules/electron/index.js:14:11)
> at Object. (/Volumes/UNTITLED/BlogHelper-master/node_modules/electron/index.js:18:18)
> 
> 删掉重装
> npm install electron --verbose
> 
> 还是一样的报错
> 
> 1. 用于问题复现的数据：

solved by:
npm install electron-prebuilt --save-dev
